// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK6rebbt152PzhVdsAL3KBwic38kLNMcA',
    appId: '1:1010589985018:web:a284de1c7a3427dc9a8143',
    messagingSenderId: '1010589985018',
    projectId: 'casino-onecard',
    authDomain: 'casino-onecard.firebaseapp.com',
    storageBucket: 'casino-onecard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_0amwFh8o_jqXlV91zIqE65tb8fkrU08',
    appId: '1:1010589985018:android:3f50ad234a762ce09a8143',
    messagingSenderId: '1010589985018',
    projectId: 'casino-onecard',
    storageBucket: 'casino-onecard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoF89OutReoKj32o6wZ4em0jUYNtG7Ui0',
    appId: '1:1010589985018:ios:8d6942470b61ad5b9a8143',
    messagingSenderId: '1010589985018',
    projectId: 'casino-onecard',
    storageBucket: 'casino-onecard.appspot.com',
    iosClientId: '1010589985018-hqnbmbms1gfvkkhqfm251cnj8j938n0f.apps.googleusercontent.com',
    iosBundleId: 'com.yoooy.onecard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoF89OutReoKj32o6wZ4em0jUYNtG7Ui0',
    appId: '1:1010589985018:ios:6b9925ab60beb2ab9a8143',
    messagingSenderId: '1010589985018',
    projectId: 'casino-onecard',
    storageBucket: 'casino-onecard.appspot.com',
    iosClientId: '1010589985018-tjrullikg4qehrh2k777ad4p437acj20.apps.googleusercontent.com',
    iosBundleId: 'com.yoooy.onecard.RunnerTests',
  );
}
